### ISSUE TITLE
WDN Pagination CSS on UNLcms pages

### ISSUE THREAD

**Issue by saltybeagle** [unlcms/unl_four#11]
http://unlcms.unl.edu/fpa/news/theatre-and-film
![screen shot 2013-10-17 at 1 32 45 pm](https://f.cloud.github.com/assets/92284/1354775/919f9dce-375a-11e3-8eeb-447737c3a29a.png)

**Comment by ericras** [comment]
Needs to load 4.0 path rather than 3.0

https://github.com/unlcms/unl_four/blob/3f3dc6916788b92b8961fe8b647330f0a15dba33/template.php#L529
